disabled = false
languageCode = "pt"
languageName = "Português"
weight = 1
title = "Carlos Cardoso"
contentDir = 'content/pt'

[params]
displayName = "Português"
isoCode = "pt"
rtl = false
dateFormat = "2 January 2006"
