disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Carlos Cardoso"
contentDir = 'content/en'

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
